branches:
  only:
  - master
  - develop
  - review

sudo: false
language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.3


    # The SDK version used to compile your project
    - android-23

    # Additional components
    # - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25
    # - sys-img-x86-android-17

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

jdk:
  - oraclejdk8


script:
  - ./gradlew build

deploy:
  provider: script
  skip_cleanup: true
  script: ./gradlew bintrayUpload
  on:
    all_branches: true
